tango: Improved versions: check for argument etc.

diff --git a/tango/bin/edna-tango-server-start b/tango/bin/edna-tango-server-start
--- a/tango/bin/edna-tango-server-start
+++ b/tango/bin/edna-tango-server-start
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 #
 #    Project: Tango
 #             http://www.edna-site.org
@@ -24,30 +24,53 @@
 #    and the GNU Lesser General Public License  along with this program.  
 #    If not, see <http://www.gnu.org/licenses/>.
 #
+
+# Check that we have one and only one argument: the name of the edna server
+if [ $# -ne 1 ]; then
+    echo "Usage: $(basename $0) name-of-edna-tango-server"
+    exit 1
+fi
+
+# Check if notifd is started - needed for TANGO events
 testit=$(pgrep notifd)
 if [ "$testit" = "" ]; then
-  LD_LIBRARY_PATH=/segfs/tango/release/centos5/lib/:$LD_LIBRARY_PATH /segfs/tango/release/centos5_64/bin/notifd -n >>/dev/null 2>&1 & 
-  sleep 3 
-  LD_LIBRARY_PATH=/segfs/tango/release/centos5/lib/:$LD_LIBRARY_PATH /segfs/tango/release/centos5_64/bin/notifd2db
-  sleep 3
+  # Check if notifd is installed
+  pathToNotifd=$(command -v notifd)
+  if [ "$pathToNotifd" = "" ]; then
+    echo "ERROR! Cannot locate notifd needed for TANGO events!"
+    exit 1
+  fi
+  notifd -n >>/dev/null 2>&1 & 
+  sleep 1
+  # Run notifd2db
+  pathToNotifd2db=$(command -v notifd2db)
+  if [ "$pathToNotifd2db" = "" ]; then
+    # Try local TANGO installation
+    export PATH=/usr/lib/tango:$PATH
+	pathToNotifd2db=$(command -v notifd2db)
+  	if [ "$pathToNotifd2db" = "" ]; then
+      echo "ERROR! Cannot locate notifd2db needed for TANGO events!"
+      exit 1
+    fi
+  fi
+  notifd2db
+  sleep 1
 fi
 
 if [ ! -d ${HOME}/log ];
 then
-    mkdir ${HOME}/log
+  mkdir ${HOME}/log
 fi
 now=$(date +"%Y%m%dT%H%M%S")
 
 baseLog=/tmp
 export TestSpace=$baseLog/edna-$now
 export log=${HOME}/log/tango-edna-${now}
-if [ ! -d ${TestSpace} ] ;
-then
-	mkdir ${TestSpace}
-	fi
+if [ ! -d ${TestSpace} ]; then
+  mkdir ${TestSpace}
+fi
 
 PythonProg=$(dirname $0)/tango-EdnaDS.py
-echo "Server Mode"
 cd $TestSpace
 #nohup $PYTHON $PythonProg ${1:+"$@"} > ${HOME}/log/edna-tango-$(date +"%Y%m%dT%H%M%S").log 2>&1 &
 $PYTHON $PythonProg ${1:+"$@"} 
